name: Go Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build for all platforms
        run: make build-all

      - name: Create compressed packages
        run: |
          cd dist
          for dir in */; do
            if [ -d "$dir" ]; then
              platform=$(basename "$dir")
              echo "Creating package for $platform"
              if [[ "$platform" == *"windows"* ]]; then
                cd "$dir" && zip -r "../joystick-gpio-$platform.zip" ./* && cd ..
              else
                cd "$dir" && tar -czf "../joystick-gpio-$platform.tar.gz" ./* && cd ..
              fi
            fi
          done

      - name: Get release ID
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ github.ref_name }}'
            });
            return release.id;

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.result }}/assets
          asset_path: dist/joystick-gpio-${{ matrix.platform }}.tar.gz
          asset_name: joystick-gpio-${{ matrix.platform }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}