name: Go Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录，用于版本检测

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build for all platforms
        run: make build-all

      - name: List built files
        run: find dist -type f -name "joystick-gpio*" | sort

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: joystick-gpio-binaries
          path: dist/
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: joystick-gpio-binaries
          path: dist

      - name: Create release packages
        run: |
          cd dist
          for dir in */; do
            if [ -d "$dir" ]; then
              platform=$(basename "$dir")
              if [[ "$platform" == *"windows"* ]]; then
                zip -r "joystick-gpio-$platform.zip" "$platform"
              else
                tar -czf "joystick-gpio-$platform.tar.gz" "$platform"
              fi
            fi
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz dist/*.zip